### ISSUE TITLE
gulp patternlab:watch on docs/advanced-auto-regenerate.html

### ISSUE THREAD

**Issue by delnolan** [pattern-lab/website#107]
Hey guys,

I'm using the gulp edition of patternlab.
I tried to use gulp patternlab:watch as per the documentation which didn't work.

What does work is gulp patternlab:build --watch.

So if you could update the docs to reflect this or add back in the watch task on gulp version it might save some other poor soul some time.

Cheers,
Derek.

PS: Love the work, keep it up.

**Comment by bmuenzenmeyer** [comment]
Thanks for letting us know.  Care to open a PR yourself? We'd love more
scrutiny and contribution from the community.
Thanks!

**Comment by delnolan** [comment]
Do you know what... I will!
I'm a little caught for time at the moment but will circle back soon.
