### ISSUE TITLE
What's the licence for website assets?

### ISSUE THREAD

**Issue by andriokha** [pattern-lab/website#118]
Hi,

I was hoping to ~steal~ use some of the images (probably just the atomic design image) and video (again that neat homepage video for AD!) from the website in a presentation on Pattern Lab. I couldn't see any information on whether that's allowed?

Thanks so much!

Andy

**Comment by bradfrost** [comment]
@andriokha yep you're free to use them so long as you provide the proper [attribution](https://creativecommons.org/licenses/by/3.0/us/). Thanks!
