### ISSUE TITLE
Adding instructions for generating site on Windows with XAMPP

### ISSUE THREAD

**Issue by illepic** [pattern-lab/website#14]
I could put in a pull request for this if you'd like, but the instructions for getting [Pattern Lab to compile](http://pattern-lab.info/docs/first-run.html) on Windows via XAMPP look like this:

1. Navigate to the root of Pattern Lab in Windows Command Prompt
2. Run `C:\xampp\php\php.exe core\builder.php -g` (assuming XAMPP is installed at the root of C:\)

All Pattern Lab scripts can be run this way (including -wr). Of course, a Windows user could always [add XAMPP's php to the path environment variable](https://stackoverflow.com/questions/10753024/how-to-access-the-command-line-for-xampp-on-windows), but that might be a little out of scope for the site!

**Comment by ijohnnatividad** [comment]
Wow! It really helps.. Thanks illepic!

**Comment by bradfrost** [comment]
@dmolsen Has this been taken care of? Trying to clean up these issues, so feel free to close this out if it's addressed.

**Comment by dmolsen** [comment]
I'm not going to end up supporting something specific like that in my directions. Closing because I won't be fixing it.
