### ISSUE TITLE
Images embeded in docs?

### ISSUE THREAD

**Issue by dmolsen** [pattern-lab/website#15]
While I can do code examples easily enough it might be nice to have images that show off a feature like Pattern States. The doc for it is dry and doesn't make much sense without the example. Maybe come up with a default image style?

**Comment by bradfrost** [comment]
@frostyweather we'll need to include some base styles for `img` tags that appear within the documentation body.

**Comment by frostyweather** [comment]
What sort of styles are you looking to add to the base styles? Should be able to target images within .content to do this.

**Comment by bradfrost** [comment]
@frostyweather yeah `.content img { display: block; margin-bottom: 1rem; }` or something is what I'm thinking.
