### ISSUE TITLE
Put CloudFlare CDN in front of site?

### ISSUE THREAD

**Issue by benedfit** [pattern-lab/website#26]
@dmolsen @bradfrost: I've had success with putting the free version of CloudFlare in front of my personal site, both from a performance, and an up-time perspective due to their 'always up' functionality. Happy to help if you're interested in doing the same.

**Comment by bradfrost** [comment]
@benedfit You'll be pleased to know that we're now hosting the site through Github Pages (via #37). Closing this out!

By the way, Chocolatey CDN Goodness is a great band name.
