### ISSUE TITLE
Clean Up Resources page

### ISSUE THREAD

**Issue by bradfrost** [pattern-lab/website#32]
I've been considering removing the resources page from the Pattern Lab project and instead redirecting it over to [Styleguides.io](http://styleguides.io/). The links are mostly duplicates and I'm trying to consolidate my resource-gathering efforts in one place. 

The only hesitation I have is that it would be great to keep a list of examples of Pattern Lab out in the wild. I think we can have a place for that (maybe even just a gist) that doesn't necessitate its own resources page.

Thoughts?

**Comment by bmuenzenmeyer** [comment]
:+1: 

I agree there is some duplication, but the "pattern lab" section within resources seems unique (no mention of entertainment weekly or tech crunch for example on styleguides.io). 

I'd also like a place to post my recent article on [pattern lab + jekyll](http://www.brianmuenzenmeyer.com/using-patternlab-to-design-build-and-maintain-a-website/) but this might be best placed in the advanced features section of `docs/index.html`? I was going to put it in `resources` but this has made me pause.

**Comment by dmolsen** [comment]
I would cull that page down to just the generic atomic design and pattern lab resources. I think the two are so linked it makes sense to at least refer to them. It's good for SEO too.

**Comment by bradfrost** [comment]
Alright, what I'll do is remove all the generic styleguide resources, provide a link to Styleguides.io, and retain/refine the atomic design and Pattern Lab resources.

Thanks guys!

**Comment by bradfrost** [comment]
This is going to be addressed in #55. Closing this out now.
