### ISSUE TITLE
Find a home for ports on the website

### ISSUE THREAD

**Issue by bmuenzenmeyer** [pattern-lab/website#33]
_Before I go all pull-request crazy on the site, I want to make sure the following is appropriate to the vision @dmolsen and @bradfrost have...._

 It would be great if there was a place to highlight things pertaining forks:

1. the fact that forks exist beyond PHP
2. documentation
3. articles
4. examples in the wild

##### (1) Existence of Forks
![image](https://cloud.githubusercontent.com/assets/298435/5691670/06da16c8-9899-11e4-9af8-d76abd156621.png)

it would be nice if there was some way to reference the forks at this level of primacy on the site. Even if it was something as simple as this:

![image](https://cloud.githubusercontent.com/assets/298435/5691699/55daacd8-9899-11e4-88e0-ea3045fa3e74.png)

Alternatives would be to place it only in the footer or in the `resources` section, depending on #32.

##### (2) Documentation
There is some existing documentation that needs to be tweaked for patternlab-node. There is some that is missing and needs to be created. In both cases I would like to use the existing structure. If the doc page exists, adding some styling to emphasize the patternlab node specific portion at the end would be great. If the page is only node-specific, say so in the title of the page. 

Perhaps a new h4 for it all?

##### (3 and 4) Articles and Examples
These can probably go in the `resources` section, depending on #32. 

----
Thoughts?

**Comment by dmolsen** [comment]
I'm hesitant to call them "forks." I realize that in practice the .NET and Node versions are that but "fork" is just an ugly word to me. "Port" is a better phrase even if it's not 1-to-1 feature-wise. I could see having a page that listed each "port" and, eventually, that "port's" spec-compliance. This include .NET with a reference that it's essentially abandoned.

On docs... my issue is that I feel like PL1 and PL2 docs need to exist the same time. I could see doing a structure like:

* /docs/ (_mentions each port and major versions_)
* /docs/node/ (_could include a v* here if you want_)
* /docs/php/ (_mentioning individual versions_)
* /docs/php/v1/ (_any request for /docs/ other than home gets routed here_)
* /docs/php/v2/

Then we need to tweak the top of the doc pages to reference port and version information for the doc page. Would this lead to a certain amount of duplication? Sure. Will it give us freedom to upgrade against spec or push spec as we each see fit? Yes.

And I'd keep "resources."

**Comment by bmuenzenmeyer** [comment]
I understand what you mean by forks/ports. I will leave the front page up to you guys - and will start working on the /docs/node/ work in the near future.

**Comment by bmuenzenmeyer** [comment]
#34 Opened to start the PL Node version of docs

**Comment by bmuenzenmeyer** [comment]
Interesting UI for comparing functionality: http://sass-compatibility.github.io/

**Comment by bradfrost** [comment]
This has been addressed with the [downloads page](http://patternlab.io/download.html). Closing this out.
