### ISSUE TITLE
Host website through Github

### ISSUE THREAD

**Issue by bradfrost** [pattern-lab/website#37]
We have `demo` and `dev` subdomains for the demo and development version respectively, but the actual website can probably be moved to a `gh-pages` branch to make posting changes a lot easier.

**Comment by bmuenzenmeyer** [comment]
:+1: :+1: 

this would likely re-ignite my desire to get the node docs there too

**Comment by bradfrost** [comment]
@bmuenzenmeyer nice. Me and @frostyweather are going to be tackling a redesign of the site, and the documentation will definitely be a part of that process. I still think tabs would be the most appropriate pattern to employ in order to cover PHP, node, and whatever future languages as well. You'll of course be consulted when we get around to it.

**Comment by bmuenzenmeyer** [comment]
Awesome Brad! I have a lot of the core documentation complete in `.md` form in some branch around here, so will wait for your lead as far as how to best incorporate it. 

Tabs do seem like a good way to go. I've been on the lookout at other libraries as I encounter them. Here's just a few for inspiration:

* [Browser Sync Multi-platform documentation](http://www.browsersync.io/docs/) 
* [Jasmine Multi-version documentation](http://jasmine.github.io/) 
  * [Docco](http://jashkenas.github.io/docco/) - extracts and formats source code inline (not perfect but neat!) It's what Jasmine, Backbone, Underscore use, etc.

**Comment by bradfrost** [comment]
Sounds good. We'll definitely keep these in mind when we get to it!

**Comment by bradfrost** [comment]
This is done! The website is now hosted on a `gh-pages` branch, which means that all changes pushed to that repo will automatically be reflected on http://patternlab.io.

Note that http://demo.patternlab.io/ is not hosted on Github.
