### ISSUE TITLE
Long code snippets break layout in Firefox

### ISSUE THREAD

**Issue by evoactivity** [pattern-lab/website#38]
The overflow on the pre element doesn't work in firefox.

Issue can be seen on this page http://patternlab.io/docs/data-json-mustache.html

**Comment by bradfrost** [comment]
@evoactivity Thanks for bringing this to my attention. We're going to be working on a new design for the site so we will address it. Looks like adding `white-space: initial` fixes the issue, so I'll see if I can squeeze that in.

Thanks again!

**Comment by bmuenzenmeyer** [comment]
+1 to this on the dev version too.
![image](https://cloud.githubusercontent.com/assets/298435/11552770/fd4172b2-994d-11e5-9007-c20c55ae31cf.png)

**Comment by bradfrost** [comment]
Cool we'll be looking more into code snippets and syntax highlighting with the new version. Thanks!

**Comment by frostyweather** [comment]
This has been addressed in the dev version by adding a max-width to the content of the page.

**Comment by dap6000** [comment]
Hey @bradfrost, this is the same issue that was mis-filed (twice) over in the other repo. It looks like in the dev branch there is now a rule for `max-width: 44em;` for the `.content` selector. Line 1018 in patternlabsite/css/style.scss. I don't see a an equivalent style in the _site directory version of that file. I'm not sure if there _needs_ to be.

Once the `max-width` rule make it into master and on to production you can close this issue and _all_ the other issues that have been filed about it.

Good work @frostyweather.

**Comment by bradfrost** [comment]
The code overflow option has been addressed in the new design. Closing this out.
