### ISSUE TITLE
Point resources to styleguides.io

### ISSUE THREAD

**Issue by bradfrost** [pattern-lab/website#39]
Realizing the resources on this page are rotted and old, so I think it would make logical sense to take people over to [styleguides.io](http://styleguides.io), which is actively maintained.

I still think there's room to have Pattern Lab-specific resources (especially examples), but I don't think I have the capacity to maintain another resource page. Maybe if we host through Github pages (#37) it will be easy to add resources right from the repository.

But in the meantime, update the header and footer nav to point to Stylguides.io

**Comment by bmuenzenmeyer** [comment]
Plus one to hosting via github. :)

**Comment by bradfrost** [comment]
See #55 for how we'll handle resources.

> Maybe if we host through Github pages (#37) it will be easy to add resources right from the repository.

And hey! The site is now hosted on Github so we're good!
