### ISSUE TITLE
960px width

### ISSUE THREAD

**Issue by wookoouk** [pattern-lab/website#40]
At exactly a window width of 960px the columns ('gi') stop working correctly and bunch up to one side.

**Comment by wookoouk** [comment]
It appears this issue happens inside a "g g-4up" but not in a "g g-3up".

**Comment by bradfrost** [comment]
Hey @wookoouk,
Thanks for the heads up. We're actually in the process of redesigning the site so soon this won't be an issue. Appreciate the eagle eye though!
