### ISSUE TITLE
Reconsider striping on documentation home page

### ISSUE THREAD

**Issue by bmuenzenmeyer** [pattern-lab/website#41]
Hi!
Overall I love the angular theme to the new look.

This is a little jarring when scrolling:

![image](https://cloud.githubusercontent.com/assets/298435/11487519/6b2af69c-9785-11e5-9d3e-d86388a235da.png)

Something a tad, lighter, yet still with the scale, like this, might be easier on the eye:

![image](https://cloud.githubusercontent.com/assets/298435/11487578/c7cf4740-9785-11e5-97a4-d4f4ff614944.png)

Just two cents as I start looking at documentation. Thanks

**Comment by bradfrost** [comment]
Thanks! The design certainly isn't final, so I'll keep this in mind.

**Comment by bradfrost** [comment]
Old design! Closing out.
