### ISSUE TITLE
Deeplinking to a #php or #node page does not load the header or footer

### ISSUE THREAD

**Issue by bmuenzenmeyer** [pattern-lab/website#42]
When constructing documentation for Node, I may want to reference another doc page, like so.

[http://localhost:4000/docs/advanced-reload-browser.html#node](http://localhost:4000/docs/advanced-reload-browser.html#node)

Doing so produces the following results, missing header and footer.

![image](https://cloud.githubusercontent.com/assets/298435/11554500/433a79ca-995e-11e5-871a-a4f598044b8f.png)

A reload fixes it, so I don't know it's its some weird local jekyll stuff or what. Someone else should test it. Relative urls didnt appear to work but it is 1:37AM afterall so :zzz:

**Comment by bradfrost** [comment]
Thanks for this. My suspicion is related to a bug me and @frostyweather ran into with hashes and the fact that `overflow: hidden` is set to the over-arching container in order to clip the header and footer angles. Will look into this.

**Comment by bradfrost** [comment]
@bmuenzenmeyer in the meantime, I'd still link things up the way you want them!

**Comment by bradfrost** [comment]
This has been addressed with the new design. See:
- http://patternlab.io/docs/command-line.html#node
- http://patternlab.io/docs/command-line.html#php

Closing this out.
