### ISSUE TITLE
Delete pattern-converting.md

### ISSUE THREAD

**Issue by bmuenzenmeyer** [pattern-lab/website#43]
https://github.com/pattern-lab/website/blob/dev/patternlabsite/docs/pattern-converting.md
I believe this file is not linked anywhere. 
Worth keeping after all this time?

**Comment by mkkwon** [comment]
http://patternlab.io/docs/pattern-converting.html

Maybe. There might be external links and references to this page, even though the original pattern lab has been deprecated.

**Comment by bradfrost** [comment]
At this point this piece of documentation is obsolete. I've deleted the file and am closing this out.
