### ISSUE TITLE
Add Prism Syntax Highlighting

### ISSUE THREAD

**Issue by bradfrost** [pattern-lab/website#44]
We want to add [Prism](http://prismjs.com/) for code syntax highlighting in order to make the documents easier to read.

**Comment by bmuenzenmeyer** [comment]
:+1: !

**Comment by frostyweather** [comment]
Implemented Prism Into the Pattern Lab site. Added prism.js and prism.css. Used the Red Carpet method (using the three tick marks) in the markdown to define what areas were ```<pre><code>``` sections Sadly, prism does not recognize mustache, json, or command prompts in the terminal from what I could find.

**Comment by bmuenzenmeyer** [comment]
@frostyweather - You might be able to get away with styling mustache and JSON as HTML and JavaScript, respectively. I'll give it a whirl in a bit.

**Comment by frostyweather** [comment]
Just tried the javascript for the JSON file. It definitely added color. Not sure exactly what it should look like though.

![screen shot 2015-12-09 at 1 32 02 am](https://cloud.githubusercontent.com/assets/13662843/11678334/d29e0bee-9e14-11e5-8e61-51b082253ab1.png)

**Comment by frostyweather** [comment]
Added ```javascript``` to markdown for the documentation for json code inside ```<pre><code>``` tags. Mustache will stay white since adding ```html``` as a language for solely mustache language doesn't change the color anyways. Everything is taken care of. Close #44

**Comment by dmolsen** [comment]
:fireworks:
