### ISSUE TITLE
Adding Annotations page is broken

### ISSUE THREAD

**Issue by mkkwon** [pattern-lab/website#46]
In the latest version of Chrome, the pattern-adding-annotations.html page is broken. See screenshot here: 
![screen shot 2016-02-03 at 6 34 51 pm](https://cloud.githubusercontent.com/assets/558258/12804114/ed20b50e-caa4-11e5-86b1-4cec50723f4b.png)

There is probably a broken tag somewhere, but for some reason, I cannot build the jekyll site in my local machine. Does anyone have a quick link to how-to run and build this site? Thanks!

**Comment by bradfrost** [comment]
@mkkwon This has been resolved
