### ISSUE TITLE
Review new design

### ISSUE THREAD

**Issue by bradfrost** [pattern-lab/website#51]
@dmolsen @bmuenzenmeyer heyo! Just letting you know the new design is almost done. Here's what the homepage is looking like:

![screencapture-127-0-0-1-4000-1466175678526](https://cloud.githubusercontent.com/assets/383701/16154944/1f2cd81c-347b-11e6-8e67-d4bae67853c8.png)

 If you want to pull down the `dev` branch and review everything, that would be great. Comments and feedback welcome!

**Comment by bmuenzenmeyer** [comment]
@bradfrost awesome! Thanks so much for sharing. Very neat to see this coming together.

I am having trouble installing ruby/jekyll on my Windows machine today, but the only small thing that stuck out to me on first glance was what I would describe as the "scaling" of the PL Logo as a background. What would it look like if it was instead "grided" similar to the organisms image?

![image](https://cloud.githubusercontent.com/assets/298435/16156149/68bbbc08-3478-11e6-83e9-e6d82fdc7bb3.png)

To me, this feels more aligned with the existing imagery and atomic design analogy. Also - are you concerned at all with enough contrast with that background behind text? it's hard to tell from the screenshot if it's an issue.

Other than that, I love the strong typography and layout. Great work!

**Comment by bradfrost** [comment]
@bmuenzenmeyer you're reading my mind! Those background patterns are placeholder for now, and I'm in the process of making an organism pattern. And yep, I'll be playing with the contrast to make sure things are legible and accessible.

**Comment by dmolsen** [comment]
Geez, you're such a better organizer/writer than me. My only concern was the background contrast. Sounds like that will be addressed. Hits all the high points for me though.

**Comment by bradfrost** [comment]
Oh! And be sure to check out the video my friend is conjuring up. It looks freaking awesome and really drives the concept home I think.

**Comment by bradfrost** [comment]
Well the new site is up! The styling still needs tweaked a bit, especially on large screens, but it's done enough to close this out.
