### ISSUE TITLE
How to handle "download" link?

### ISSUE THREAD

**Issue by bradfrost** [pattern-lab/website#52]
@dmolsen @bmuenzenmeyer I'm wondering how we should handle the "Download" link on Pattern Lab's site. Obviously, there's no one repo to point people to, so I'm wondering if we Should we have a dedicated page that runs through the various options? Looking for some advice on where's the best place to point people to.

**Comment by bmuenzenmeyer** [comment]
Having a `Download / Getting Started Page` makes a lot of sense. 

Now with the rise of our [canned editions](https://github.com/pattern-lab?utf8=%E2%9C%93&query=edition), users may choose their own adventure more so than ever. 

Inside each of those are options too, like whether to download a prebuilt version, use composer, or use npm.

I've modeled my edition READMEs ([edition node gulp example](https://github.com/pattern-lab/edition-node-gulp)) after what Dave built for PL/PHP, and they seem to offer a great landing point after you make your initial decision about which flavor you want. Pointing directly to these would be simplest in my opinion.

Eventually, I could see a break down of PHP and Node Editions, and then perhaps a list of starterkits 
that apply. 

A contributing page could also be setup someday to describe how to hack against the ecosystem, what conventions we use, etc.

**Comment by bmuenzenmeyer** [comment]
I'd also add that we could reference some of the thoughts put into https://github.com/pattern-lab/docs/issues/2

**Comment by dmolsen** [comment]
@bmuenzenmeyer's on the right track. I think it could be ordered like:

```
Pattern Lab for PHP
The PHP version of Pattern Lab comes in the following flavors: 

   Mustache Edition
   This edition uses the [Mustache template language](link to Mustache doc) and can be installed via:
      - [Zip](it'd point to the releases page)
      - [Composer]it('d point to the README as Brian notes)

   Twig Edition
   This edition uses the [Twig template language](link to Twig doc) and can be installed via:
      - [Zip](it'd point to the releases page)
      - [Composer]it('d point to the README as Brian notes)

   Drupal Edition
   This edition uses the [Twig template language](link to Twig doc) and is built to work with Drupal. Please refer to the README for installation instructions.
```

A similar layout for Node? I need to migrate `pattern-lab/php` to be home of the Mustache Edition. I can do that to coincide with the new site. I will end up also creating a repo that follows our naming convention but it'll just point people back to `pattern-lab/php`. 

All of this is going to need to evolve though. I'll have plug-ins for PHP. A Faker plugin will be available this weekend. KSS will come along sometime in July. And obviously the StarterKits though I think we still need to bake those some.

**Comment by bmuenzenmeyer** [comment]
> A similar layout for Node?

You summarized this very nicely - :+1:

**Comment by bradfrost** [comment]
Alright, that sounds good. I'm looping in @frostyweather to set up the skeleton of this page and then we can tweak from there.

**Comment by dmolsen** [comment]
Please edit my copy as you see fit. I'm wordy/technical.

**Comment by bradfrost** [comment]
There's now a dedicated `download.html` page. Closing this out.
