### ISSUE TITLE
Redirect /about.html to atomicdesign.bradfrost.com

### ISSUE THREAD

**Issue by bradfrost** [pattern-lab/website#53]
Right now there are quite a few inbound links on the internet to http://patternlab.io/about.html as it provides an overview of what atomic design is. For simplicity's sake, I'd prefer to point people to http://atomicdesign.bradfrost.com/chapter-2/

Because we want to host the PL website on Github, we may need to do a client-side redirect rather than a server-side redirect. @bmuenzenmeyer do you happen to know if Github provides `.htaccess` access or anything like that? It's not the worst thing in the world to do a JS redirect.

**Comment by bmuenzenmeyer** [comment]
I can't say I've ever encountered `.htaccess` in the documentation, but this looks promising!

https://help.github.com/articles/redirects-on-github-pages/

**Comment by bradfrost** [comment]
Oh hey, how about that! Thanks a bunch.

**Comment by DirtyF** [comment]
FYI https://github.com/jekyll/jekyll-redirect-from#redirect-to

**Comment by bradfrost** [comment]
I'm going to close this out, as I haven't heard people complain either here or to me personally about this issue.
