### ISSUE TITLE
Add Copy/Point Links To Right Direction in Downloads Page

### ISSUE THREAD

**Issue by frostyweather** [pattern-lab/website#54]
Add better copy to the different options and point the links to the correct zip files and GitHub repositories.

Current downloads page looks like this:

![screen shot 2016-06-29 at 4 16 47 pm](https://cloud.githubusercontent.com/assets/13662843/16467498/9fd8309e-3e15-11e6-8e2b-f206b8eae812.png)

**Comment by bmuenzenmeyer** [comment]
@frostyweather Hi Ian! This is a good start and I like how it extends the look and feel of the homepage. I'd like to alter the Node quadrant a bit, since it ships with two flavors, Gulp and Grunt. Mind if I hack on that idea a bit and submit a PR?

**Comment by dmolsen** [comment]
That layout isn't going to work long-term. It's more like this:

```
PHP
   - Mustache Edition
     Install options.
   - Twig Edition
     Install options
   - Drupal Edition
     Install options
   - Thin Edition
     Install options
Node
   - Gulp Edition
     Install options.
   - Grunt Edition
     Install options
```
And I'm not sure how @bmuenzenmeyer is planning on how to tackle Pattern Engines within the context of Gulp/Grunt so that's another wrinkle.

And rather than links directly to Zip/Composer or NPM or whatever maybe we have a standard "install instructions" in a README for each project? We sort of have now that.

**Comment by bmuenzenmeyer** [comment]
@dmolsen is right - it's hard to encapsulate all possible options here.... and most of the readmes have a ton of info already.  I'll still try to mockup or build something that makes a bit more sense if I find time.

**Comment by frostyweather** [comment]
Good to know. I had it set up similar to the way you laid out it with just a Node and PHP section @dmolsen, but Brad wanted to separate them out and put PHP and Node at the top followed by the different editions. So you want just 1 option under each edition linking to the GitHub repository or what? Also there are so many GitHub repositories (Pattern Engines, standard-edition, etc.) I wasn't sure where to point each link.

**Comment by dmolsen** [comment]
Or maybe a two column layout. PHP on left and Node on right and then we fill in as necessary?

**Comment by bradfrost** [comment]
@dmolsen @bmuenzenmeyer to elaborate on what @frostyweather is saying, I think it's important to have the main PHP and Node projects front and center. Simply from a source order standpoint, listing out all the PHP-based projects before getting to the Node version totally diminishes all the hard work Brian's done.

**Comment by bradfrost** [comment]
We had a treatment in place that stacks each option, and Node was waaaaay down there. 

As a user of software, my mentality when hitting a download page is "GIVE ME THE DAMN LINK." I don't want the 32-bit and 64-bit options, the legacy, or tangential options.

**Comment by bradfrost** [comment]
I feel like the description text can be helpful to clarify things, such as "The Twig Edition is a variation of the PHP edition that uses the popular Twig templating engine as the pattern engine."

**Comment by dmolsen** [comment]
@bradfrost -

Wasn't trying to suggest a layout. Just noting the volume of options and their relationship to each other. Personally I'd go two columns. And I'm happy if it says something like:

```
PHP
You can pick the version of Pattern Lab you'd like based on template language or environment:
  - Mustache
  - Twig
  - Drupal
```
And those go off to the appropriate repo README where I can clean up install instructions.

**Comment by frostyweather** [comment]
Changed up the formatting into the 2 column layout mentioned earlier. Chances are, most folks won't be downloading PL from their phones at this point in time, so the two column layout makes sense to show both Node and PHP importance
![screen shot 2016-06-29 at 6 51 45 pm](https://cloud.githubusercontent.com/assets/13662843/16471426/a895067a-3e2a-11e6-845e-9d4c00212a16.png)
![screen shot 2016-06-29 at 6 53 32 pm](https://cloud.githubusercontent.com/assets/13662843/16471456/d0590f4e-3e2a-11e6-9f33-06e1e0c7c170.png)

. I took the links away from the links since I am not sure exactly which GitHub Repos to link them to.

**Comment by frostyweather** [comment]
Can @dmolsen and @bmuenzenmeyer provide the correct GitHub repo links for the Editions listed above for PHP and Node Versions? That would help me out as we finish up this site. Thanks.

**Comment by bmuenzenmeyer** [comment]
Edition Node Gulp - https://github.com/pattern-lab/edition-node-gulp 
Edition Node Grunt - https://github.com/pattern-lab/edition-node-grunt

**Comment by frostyweather** [comment]
Thanks @bmuenzenmeyer. Once I get the PHP ones we'll be all set.

**Comment by bradfrost** [comment]
It looks like all the links are in place, so I'm closing this out.
