### ISSUE TITLE
Broken layout in Firefox

### ISSUE THREAD

**Issue by bradfrost** [pattern-lab/website#56]
The docs page aren't displaying as a two-column layout in Firefox.

<img width="1280" alt="editing the configuration options pattern lab" src="https://cloud.githubusercontent.com/assets/383701/16548590/4f77ca80-4160-11e6-8518-367df5fa7726.png">

@frostyweather, can you address?

**Comment by frostyweather** [comment]
Fixed this by getting rid of flex: 1 on .content. Works now. Close #56

**Comment by bradfrost** [comment]
Removing that causes the sidebar not to appear flush to the right.

<img width="1280" alt="installation pattern lab" src="https://cloud.githubusercontent.com/assets/383701/16549569/85c9b9be-416e-11e6-9a66-ff0704d8d0d6.png">

**Comment by frostyweather** [comment]
This should be fixed now. Added flex 1 to the sidebar instead. Close #56
