### ISSUE TITLE
Lighten `organism-pattern.svg`

### ISSUE THREAD

**Issue by bradfrost** [pattern-lab/website#57]
The `organism-pattern.svg` file is still a bit too high-contrast for legibility. @frostyweather can you lighten up the stroke and fill values for the SVG file? Also, the connecting dots (the smaller north/south/east/west dots) appear a bit too large. Can you scale those down?

**Comment by frostyweather** [comment]
Lightened it up. Let me know if this works

**Comment by frostyweather** [comment]
Lightened this up. Added background color to .sidebar so the organism pattern in the sidebar looks the same as the others within the site. Close #57
