### ISSUE TITLE
Update `icon-atom.svg`

### ISSUE THREAD

**Issue by bradfrost** [pattern-lab/website#58]
The spinning atom logo should match the color styles of the atom icon found in the footer. Right now the black stroke is getting lost against the dark gray background.

**Comment by frostyweather** [comment]
Fixed this within icon-atom.svg. Close #58

**Comment by bradfrost** [comment]
Looks like we'll need two versions because the docs active state looks weird:

![Uploading Screen Shot 2016-07-03 at 11.06.54 PM.png…]()

**Comment by frostyweather** [comment]
Can't see the screen shot

**Comment by bradfrost** [comment]
<img width="441" alt="adding new patterns pattern lab" src="https://cloud.githubusercontent.com/assets/383701/16569883/0895c6b2-420a-11e6-90ba-68f2da3a6d60.png">

**Comment by frostyweather** [comment]
Added icon-atom-dark.svg to assets for documenation sidebar. Close #58
![screen shot 2016-07-05 at 10 38 13 am](https://cloud.githubusercontent.com/assets/13662843/16588359/9ed3a94a-429c-11e6-8626-0ea7902c7066.png)
