### ISSUE TITLE
PHP Plugins

### ISSUE THREAD

**Issue by dmolsen** [pattern-lab/website#59]
PHP has three plugins currently. Is it ok if I add them to the PHP section of the "Download" page? Not sure how to highlight them otherwise.

**Comment by bradfrost** [comment]
Hmmm, this will require a bit of thought. I don't think including them right alongside the core downloads is a great idea. Will have a think about how to handle this, but it won't be tonight.

**Comment by dmolsen** [comment]
happy with where it is. thanks.
