### ISSUE TITLE
Add max-width for homepage video

### ISSUE THREAD

**Issue by bradfrost** [pattern-lab/website#62]
On extra large screens, the video shouldn't stretch to fit the full viewport. Cap it at a size that seems appropriate. 1200px? Something like that? 

Note that we may want to cap the entire website with the same value to prevent it from looking lousy on extra large screens.

**Comment by frostyweather** [comment]
Added max width on the homepage video and centered it. Trying to figure out the best way to cap content on the page if that since there are different layouts for each page.

**Comment by bradfrost** [comment]
@frostyweather cool, closing this out! We'll handle the container width in another issue if it's actually a problem.
