### ISSUE TITLE
On medium screens, make docs section two columns

### ISSUE THREAD

**Issue by bradfrost** [pattern-lab/website#64]
On medium screens before the sidebar appears, the category descriptions should display as two-by-two. Right now the space is stretched.

<img width="934" alt="viewing patterns on a mobile device pattern lab" src="https://cloud.githubusercontent.com/assets/383701/16566920/e8c57d6e-41e6-11e6-8156-841a94bf7550.png">

**Comment by frostyweather** [comment]
Created a 2 up grid layout on medium screens using flexbox. Close #64
![screen shot 2016-07-05 at 11 27 55 am](https://cloud.githubusercontent.com/assets/13662843/16589970/9165d15a-42a3-11e6-867c-54396c70d206.png)
