### ISSUE TITLE
"Gotcha" section examples not rendering

### ISSUE THREAD

**Issue by bmuenzenmeyer** [pattern-lab/website#66]
http://patternlab.io/docs/pattern-including.html 

This code block

```
// partials to match
00-atoms/00-global/04-test-with-picture.mustache
00-atoms/00-global/05-test.mustache
00-atoms/00-global/06-test.mustache
00-atoms/00-global/test.mustache

// using the shorthand partials syntax
{{> atoms-test }}                 // will match 00-atoms/00-global/05-test.mustache
                                  // using the shorthand syntax you'll never be able to match 06-test nor test in this scenario
{{> atoms-test-with-picture }}    // will match 00-atoms/00-global/04-test-with-picture.mustache
{{> atoms-test-wit }}             // will match 00-atoms/00-global/04-test-with-picture.mustache

// using the default mustache partials syntax
{{> atoms/global/05-test }}       // won't match anything because atoms & global are missing their digits
{{> 00-atoms/00-global/06-test }} // will match 00-atoms/00-global/06-test.mustache
```

Does not render each include

![image](https://cloud.githubusercontent.com/assets/298435/16706134/f68bd894-4565-11e6-9a17-aef7ba15df22.png)

**Comment by dmolsen** [comment]
As I noted last night, I removed the liquid raw tags when I shouldn't have. This will be fixed today.

**Comment by bradfrost** [comment]
Damn raw tags is why I'm not able to build locally.

One quick (unrelated) comment. In my own workflow and in response to other people moaning about it, I'm starting to minimize the use of the number prefixes unless I have to organize the patterns in a certain way ("i.e. `00-atoms`, but not `forms` or `blocks`). I'm thinking we remove the numbers throughout the docs to increase legibility and help people understand that the number prefixes aren't required. 

So change to `00-atoms/global/test.mustache`. Sound good?

**Comment by bmuenzenmeyer** [comment]
I'm for it.  Especially with order being added to patten.md frontmatter
soon

**Comment by dmolsen** [comment]
I believe I've removed most of the digits. Raw tags should be fixed.
