### ISSUE TITLE
URL to install GULP fails to load

### ISSUE THREAD

**Issue by davidrpoliti** [pattern-lab/website#71]
http://patternlab.io/docs/requirements.html#node
Link to Gulp repo fails to load, has extra preceding 'h' in URL

Currently points to:
hhttps://github.com/gulpjs/gulp/blob/4.0/docs/getting-started.md

Near:
"It’s also highly recommended that you **install gulp** or grunt globally."

Would submit a PR but I can't find the MD file for this PL2.0 page

**Comment by bmuenzenmeyer** [comment]
Hi @davidrpoliti 

Thanks for pointing this out! I've fixed it, and you can see exactly where by looking at the commit above, in case you want/need to poke around more of the docs and improve them in the future.

Thanks again!
