### ISSUE TITLE
404 link on Generating Pattern Lab

### ISSUE THREAD

**Issue by rjdusk** [pattern-lab/website#72]
Hi guys,
in your documentation for Generating Pattern Lab ([node tab](patternlab.io/docs/generating-pattern-lab.html#node)) the link for 'available for viewing' results in a 404. I believe it should point to here: http://patternlab.io/docs/viewing-patterns.html#node 

I couldn't find the specific md file in this repo (probably because I'm blind), to make the change.

cheers

**Comment by bmuenzenmeyer** [comment]
nice catch. PHP looked to be broken too. fixed
