### ISSUE TITLE
Document Starter Kits

### ISSUE THREAD

**Issue by bradfrost** [pattern-lab/website#77]
I realize there are a bunch of starterkits floating around, but there's no real home base for them. We should document what starter kits are, how to use them, and which starterkits are available. /cc @bmuenzenmeyer @EvanLovely

**Comment by bmuenzenmeyer** [comment]
I have a large island of documentation in my wiki -  including this: https://github.com/pattern-lab/patternlab-node/wiki/Importing-Starterkits

**Comment by bradfrost** [comment]
@bmuenzenmeyer This is great. Wrangling all this documentation will be a big task in the coming months. Ideally, we'll have all this nicely wrapped up [here](http://patternlab.io/docs/) once it's all said and done.

**Comment by bmuenzenmeyer** [comment]
I'm definitely I favor of reducing the wiki footprint! It's been convenient
but makes for fragmentation

**Comment by bradfrost** [comment]
Most certainly. One of the big things I'd love to tackle in the coming months is corralling the documentation so everything's under one roof, and to be a more human friendly. Pictures, GIFs and stuff like that.
