### ISSUE TITLE
Switch Node and PHP tabs

### ISSUE THREAD

**Issue by bradfrost** [pattern-lab/website#80]
Based on the direction of the project, it probably makes sense to switch the PHP and Node tabs so the Node tab is the default.

**Comment by bradfrost** [comment]
Closed via https://github.com/pattern-lab/website/commit/f553cad298c28a07424622ce9938b5ad7f89ae28

**Comment by bmuenzenmeyer** [comment]
@bradfrost I think something is amiss with this.

Take a look at a page like: http://patternlab.io/docs/installation.html 

The tabs indicate Node, but the content is PHP instructions.

![image](https://user-images.githubusercontent.com/298435/34994362-dd66323a-fa98-11e7-80b1-87696e88c4fc.png)

My **guess** is that the source order of all pages needs to swap too?

**Comment by bradfrost** [comment]
@bmuenzenmeyer Ah, good catch. I updated the source order of everything, but needed to change a line of JavaScript: 

```
$('#node').addClass('tabs__item--is-active');
```

In order to default to the node tab. All good now!
