### ISSUE TITLE
Font too thin on windows

### ISSUE THREAD

**Issue by mateuspv** [pattern-lab/website#91]
Hi, I notice that pattern-lab(2) font changed recently:
![font](https://user-images.githubusercontent.com/4995440/34518937-db211d58-f068-11e7-9be8-a5b15dfcfb24.png)
On windows, it's seems too thin and it's difficult to read =/

S.O: Windows 10 updated
Browser: Chrome updated
screen resolution: 1920x1080 (no retina)

Thanks!

**Comment by bradfrost** [comment]
![capture](https://user-images.githubusercontent.com/383701/35170007-a9b330c8-fd2c-11e7-910a-793e192983f7.PNG)

I can't recreate the issue here. Closing this out, but if you're still seeing this issue feel free to reopen.
