### ISSUE TITLE
HTTPS

### ISSUE THREAD

**Issue by coliff** [pattern-lab/website#94]
Now that GitHub Pages supports custom domains with SSL it'd be good to see this site use HTTPS.
REF: https://blog.github.com/2018-05-01-github-pages-custom-domains-https/

**Comment by bradfrost** [comment]
Thanks for the suggestion, @coliff. Looks like I'll have to dig into to change some records in order to make that happen.

**Comment by bradfrost** [comment]
Hey neat, Pattern Lab's website is now HTTPS! Thanks for the nudge, @coliff.

<img width="224" alt="screenshot 2018-07-21 11 32 21" src="https://user-images.githubusercontent.com/383701/43037257-c8d4b12e-8cd9-11e8-8fd1-e68ee2ccee8f.png">
